// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hneewqpvokbdvqoamfbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuZWV3cXB2b2tiZHZxb2FtZmJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMDk5NjgsImV4cCI6MjA3MTU4NTk2OH0.uWpDD0IX6sk7mDqEAhwmhKMDPjZ-mageMnfqdGSLbbE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);